### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by ivergentz** [ivergentz/capstone-project#2]
### Value statement
As a **user**
I need a page to **find rides**
so that the **user can book a provide ride **

### Description (Text, Scribble, Wireframe, Design)

![Untitled-2020-08-14-1410(2)](https://user-images.githubusercontent.com/67914070/91688432-3bc04480-eb62-11ea-8be3-7c4fb841bf4a.png)

For the first setup: Search input field on the dashboardPage. Possible to filter for the following db entries:  date & locations

### Acceptance criteria
The input field is working and is connected with the labels. Rides disappear when input starts. Autocompletion works for all the rides stored in the db. By clicking on one entry the toggle logic has to work.

### Tasks
- [ ] Create input field
- [ ] Search database for entries (matching date or destination)
- [ ] display results below input field
- [ ] implement toggle logic
- [ ] details are working
- [ ] write tests

### Complexity
medium
