### ISSUE TITLE
Show rides

### ISSUE THREAD

**Issue by ivergentz** [ivergentz/capstone-project#7]
### Value statement

**As a user**
there has to be a **dashboard showing all the booked/provided rides**
so that the user **has a quick rides overview.**

### Description (Text, Scribble, Wireframe, Design)

![Untitled-2020-08-14-1410](https://user-images.githubusercontent.com/67914070/91687430-f569e600-eb5f-11ea-8739-d9591a49c353.png)

Displayed as single cards. Comes from a json-db to just implement the dashboard before setting up the API.

### Acceptance criteria
Shows all rides createt in the json-db with:
1. Date
2. Time
3. Directions

### Tasks

- [x] set up json db with provided and booked rides
- [x] create Storybook entries
- [x] write tests
- [x] create dashboardPage
- [x] showing all the rides stored in the db

### Complexity
medium

**Comment by ivergentz** [comment]
### Value statement
As a **user**
there has to be a dashboard  showing all the booked/provided rides**
so that the **user has a quick rides overview**.

### Description (Text, Scribble, Wireframe, Design)
[Put a design here that shows:] To different styles: 
1) Provided rides
2) Booked rides
Displayed as single cards. Comes from a json-db to just implement the dashboard before setting up the API.

### Acceptance criteria
Shows all rides createt in the json-db.

### Tasks
- [ ] set up json db with provided and booked rides
- [ ] create Storybook entries
- [ ] write tests
- [ ] create dashboardPage
- [ ] showing all the rides stored in the db

### Complexity
medium
