### ISSUE TITLE
create new ride

### ISSUE THREAD

**Issue by ivergentz** [ivergentz/capstone-project#9]
### Value statement
**As a user**
I need a function to **create new rides**
so I can **provide rides for other users**

### Description (Text, Scribble, Wireframe, Design)
![Uploading create ride.png…]()

### Acceptance criteria
- navigation threw the create pages works
- rides are stored in data.json
- rides will be displayed on the dashboard page

### Tasks
- [x]  Build CreatePage and the Subpages
- [x]  All Links are working
- [x]  Rides are sotred in the data.json
- [ ]  Storybook entry written
- [ ]  tests

### Complexity
high
